export const AAD_HANDLER = "AAD_HANDLER";
export const REMOVE_HANDLER = "REMOVE_HANDLER";
export const GET_SELECT_DATA = 'GET_SELECT_DATA';
export const CHANGE_SELECT_DATA = 'CHANGE_SELECT_DATA';
export const DISCRIPTION_CALL = "DISCRIPTION_CALL";


